# postgres database deployment with persistent volume
# standard configuration with environment variables
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_NAME
          # mounting the volume to the postgres data path
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      # defining the volume based on our pvc
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc