# secret przechowuje dane wrazliwe zakodowane w base64
# echo -n "admin" | base64 -> YWRtaW4=
# echo -n "password123" | base64 -> cGFzc3dvcmQxMjM=
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQxMjM=
