# konfiguracja cache
proxy_cache_path /tmp/nginx_cache keys_zone=api_cache:10m inactive=30s;

# definicja wewnetrznego adresu backendu
upstream backend_cluster {
    server api-a:3000;
    server api-b:3000;
}

server {
    listen 80;

    # serwowanie plikow reacta i obsluga routingu spa
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # endpoint z cache ustawionym na 30 sekund
    location /api/stats {
        proxy_pass http://backend_cluster/stats;
        proxy_cache api_cache;
        proxy_cache_valid 200 30s;
        add_header X-Cache-Status $upstream_cache_status;
    }

    # przekierowanie pozostalego ruchu api do backendu
    location /api/ {
        proxy_pass http://backend_cluster/;
    }
}


